### ISSUE TITLE
Cannot Launch

### ISSUE THREAD

**Issue by justinrusso** [Danacus/RecipeViewer#2]
~~Seems not all dependencies are being installed or something~~

"Cannot find module 'hot-reload-server'" when running the exe file.
https://github.com/Danacus/RecipeViewer/blob/835569bded5af5c9f9c142c67963922a3ef531e4/main.js#L14

I noticed this library is not in the package.json, though, this is also only for development environments...

Windows 10 64-bit

**Comment by Danacus** [comment]
I'll just remove it. I don't use it anyway. I still don't understand why it's showing this error though. I'll fix it tomorrow.

**Comment by Danacus** [comment]
You're right, this module is not in package.json. For some reason, it never showed me an error. And also it shouldn't require this module in a production environment.

**Comment by justinrusso** [comment]
Must have just been installed and kept in node_modules but didnt save would be my assumption...

And yeah, I'm a bit confused on that as well... I do work on NodeJS so I suppose my env is messing with it?

**Comment by Danacus** [comment]
I've been copying stuff from different boilerplates, so that's probably why. I think my env always stays on production for some reason, or maybe not, because electron debug does get loaded only when I'm developing. I honestly don't really understand the NodeJS env thing. Maybe there is something wrong with your env, I don't know, but there's a bug in the code that's for sure.

**Comment by Danacus** [comment]
Possibly fixed in 8119833bdad2845c3bbdbb2abfe190f73651bb7f. You can try the latest release now.

**Comment by justinrusso** [comment]
Thanks! 👍
